/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ModIdea = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'author' : IDL.Opt(IDL.Principal),
  'gamePlatform' : IDL.Text,
});

export const idlService = IDL.Service({
  'createModIdea' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'getAllModIdeas' : IDL.Func([], [IDL.Vec(ModIdea)], ['query']),
  'getModIdea' : IDL.Func([IDL.Nat], [ModIdea], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ModIdea = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'author' : IDL.Opt(IDL.Principal),
    'gamePlatform' : IDL.Text,
  });
  
  return IDL.Service({
    'createModIdea' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'getAllModIdeas' : IDL.Func([], [IDL.Vec(ModIdea)], ['query']),
    'getModIdea' : IDL.Func([IDL.Nat], [ModIdea], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };